<!DOCTYPE html>
<html>

<head>
    <title>Category Report</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
            color: #333;
            margin: 20px;
        }

        h1 {
            text-align: center;
            font-size: 2.5rem;
            color: #007bff;
            margin-bottom: 10px;
        }

        p {
            text-align: center;
            font-size: 1rem;
            margin-bottom: 30px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 0 auto;
            background-color: #fff;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
        }

        th {
            background-color: #007bff;
            color: #fff;
            padding: 12px;
            text-align: center;
            font-size: 1rem;
        }

        td {
            padding: 10px;
            text-align: center;
            font-size: 0.9rem;
            border: 1px solid #ddd;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #e9ecef;
        }

        footer {
            text-align: center;
            margin-top: 20px;
            font-size: 0.8rem;
            color: #666;
        }
    </style>
</head>

<body>
    <h1>{{ $title }}</h1>
    <p>{{ $date }}</p>
    <p>Below is the report of categories available in the system:</p>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($category as $data)
                <tr>
                    <td>{{ $data->id }}</td>
                    <td>{{ $data->name }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <footer>
        Report generated by {{ config('app.name') }} &copy; {{ date('Y') }}
    </footer>
</body>

</html>
